<a href="https://colab.research.google.com/github/EllaC12345/Deep_Learning_Challenge/blob/main/AlphabetSoup_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.columns = application_df.columns.str.strip()
application_df.drop(['EIN', 'NAME'], axis=1, inplace = True)

In [3]:
# Determine the number of unique values in each column.
unique_value_count = application_df.nunique()
unique_value_count

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
APPLICATION_TYPE_count = application_df['APPLICATION_TYPE'].value_counts()
APPLICATION_TYPE_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`


# Set your chosen cutoff value
cutoff_value = 500

value_counts = application_df['APPLICATION_TYPE'].value_counts()

# Create a list of application types to be replaced with 'Other'
application_types_to_replace = value_counts[value_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_count_over_one = classification_count[classification_count > 1]
classification_count_over_one

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# Set your chosen cutoff value
cutoff_value = 500

classification_count = application_df['CLASSIFICATION'].value_counts()

# Create a list of application types to be replaced with 'Other'
classifications_to_replace = classification_count[classification_count < cutoff_value].index.tolist()


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [9]:
## splitting target from dataset
y =application_df['IS_SUCCESSFUL']
X = application_df.drop(columns = 'IS_SUCCESSFUL')
X.head(5)
y.head()

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [10]:
X.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590

In [11]:
cons = X["SPECIAL_CONSIDERATIONS"].unique()
cons

array(['N', 'Y'], dtype=object)

In [12]:
status = X["STATUS"].unique()
status

array([1, 0])

In [13]:
# Encode booloean variables
def consideration(SPECIAL_CONSIDERATIONS):
  if SPECIAL_CONSIDERATIONS == "Y":
    return 1
  else:
      return 0
# Call the encode_fee function on the fee column
X["SPECIAL_CONSIDERATIONS"] = X["SPECIAL_CONSIDERATIONS"].apply(consideration)

In [14]:
# Encode the categorical variables using get_dummies
X_transformed= pd.get_dummies(X[["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION", "INCOME_AMT"]])

## Display the transformed data
X_transformed.head()

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,AFFILIATION_CompanySponsored,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,1,...,1,0,0,1,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [15]:
# Concatenate the X_transformed and the X DataFrames
X = pd.concat([X, X_transformed], axis=1)
# Drop the original  columns
X = X.drop(columns=["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION", "INCOME_AMT"])

X.head()

,STATUS,SPECIAL_CONSIDERATIONS,ASK_AMT,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,0,5000,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,0,108590,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,1,0,5000,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
3,1,0,6692,0,0,0,1,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,1,0,142590,0,0,0,1,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [16]:
# Split our preprocessed data into our features and target arrays

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train,y_test = train_test_split(X,y, random_state = 1)
X_train.shape
X_test.shape

(8575, 43)

In [17]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
## determining # of input and neuron for modeling
input = X.columns.nunique()
input

43

## Compile, Train and Evaluate the Model

In [25]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])

    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=10,
        step=2), activation=activation, input_dim=input))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=10,
            step=2),
            activation=activation))

    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

    return nn_model

In [20]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.6-py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.9/128.9 kB 1.0 MB/s eta 0:00:00
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.14.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (23.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.31.0)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2023.11.17)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.6 kt-legacy-1.0.5

In [34]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=3)

Reloading Tuner from ./untitled_project/tuner0.json

In [35]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))
#retrieve the best hyperparameter
best_hps = tuner.oracle.get_best_trials(num_trials=1)[0].hyperparameters.values
# Print or use the best hyperparameters
print("Best Hyperparameters:", best_hps)

Trial 90 Complete [00h 01m 24s]
val_accuracy: 0.7334110736846924

Best val_accuracy So Far: 0.7344606518745422
Total elapsed time: 01h 09m 11s
Best Hyperparameters: {'activation': 'sigmoid', 'first_units': 3, 'num_layers': 2, 'units_0': 7, 'units_1': 3, 'units_2': 5, 'units_3': 3, 'units_4': 3, 'units_5': 1, 'tuner/epochs': 20, 'tuner/initial_epoch': 7, 'tuner/bracket': 2, 'tuner/round': 2, 'tuner/trial_id': '0044'}

In [36]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer based on the results of hyperparameter tuner
hidden_nodes_layer1 = 7
hidden_nodes_layer2 = 3
hidden_nodes_layer3 = 5
hidden_nodes_layer4 = 3
hidden_nodes_layer5 = 3
hidden_nodes_layer6 = 1

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(
    tf.keras.layers.Dense(units= hidden_nodes_layer1, input_dim=input, activation = 'sigmoid')
)


# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units= hidden_nodes_layer2, input_dim=input, activation = 'sigmoid')
       )
# Third hidden layer
nn_model.add(tf.keras.layers.Dense(units= hidden_nodes_layer3, input_dim=input, activation = 'sigmoid')
       )

# Fourth hidden layer
nn_model.add(tf.keras.layers.Dense(units= hidden_nodes_layer4, input_dim=input, activation = 'sigmoid')
       )

# Fith hidden layer
nn_model.add(tf.keras.layers.Dense(units= hidden_nodes_layer5, input_dim=input, activation = 'sigmoid')
       )

# Sixth hidden layer
nn_model.add(tf.keras.layers.Dense(units= hidden_nodes_layer6, input_dim=input, activation = 'sigmoid')
       )

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_7 (Dense)             (None, 7)                 308

 dense_8 (Dense)             (None, 3)                 24

 dense_9 (Dense)             (None, 5)                 20

 dense_10 (Dense)            (None, 3)                 18

 dense_11 (Dense)            (None, 3)                 12

 dense_12 (Dense)            (None, 1)                 4

 dense_13 (Dense)            (None, 1)                 2

=================================================================
Total params: 388 (1.52 KB)
Trainable params: 388 (1.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [37]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [38]:
# Train the model
fit_model= nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 4ms/step - loss: 0.7055 - accuracy: 0.4864
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6852 - accuracy: 0.5426
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6461 - accuracy: 0.7266
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6044 - accuracy: 0.7290
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5891 - accuracy: 0.7295
Epoch 6/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5840 - accuracy: 0.7293
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5817 - accuracy: 0.7295
Epoch 8/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5806 - accuracy: 0.7293
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5802 - accuracy: 0.7301
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5802 - accuracy: 0.7295
Epoch 11/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5800 - accuracy: 0.7296
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5797 - accuracy: 0.7299
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5794 - accuracy: 0.7309
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5797 - accuracy: 0.7294
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5793 - accuracy: 0.7306
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5794 - accuracy: 0.7297
Epoch 17/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5791 - accuracy: 0.7306
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5790 - accuracy: 0.7300
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5791 - accuracy: 0.7297
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5787 - accuracy: 0.7301
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5786 - accuracy: 0.7300
Epoch 22/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5788 - accuracy: 0.7294
Epoch 23/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5785 - accuracy: 0.7297
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5786 - accuracy: 0.7298
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5784 - accuracy: 0.7300
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5783 - accuracy: 0.7303
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5784 - accuracy: 0.7301
Epoch 28/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5782 - accuracy: 0.7305
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5783 - accuracy: 0.7298
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5784 - accuracy: 0.7297
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5783 - accuracy: 0.7299
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5782 - accuracy: 0.7303
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5780 - accuracy: 0.7292
Epoch 34/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5782 - accuracy: 0.7292
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5779 - accuracy: 0.7293
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5781 - accuracy: 0.7290
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5780 - accuracy: 0.7299
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5778 - accuracy: 0.7308
Epoch 39/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5779 - accuracy: 0.7303
Epoch 40/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5776 - accuracy: 0.7306
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5778 - accuracy: 0.7301
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5778 - accuracy: 0.7304
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5770 - accuracy: 0.7313
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5767 - accuracy: 0.7308
Epoch 45/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5767 - accuracy: 0.7319
Epoch 46/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5767 - accuracy: 0.7308
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5765 - accuracy: 0.7311
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5764 - accuracy: 0.7311
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5764 - accuracy: 0.7313
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5762 - accuracy: 0.7325
Epoch 51/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5763 - accuracy: 0.7304
Epoch 52/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5761 - accuracy: 0.7313
Epoch 53/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5760 - accuracy: 0.7317
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5761 - accuracy: 0.7310
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5759 - accuracy: 0.7323
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5755 - accuracy: 0.7310
Epoch 57/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5746 - accuracy: 0.7313
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5739 - accuracy: 0.7317
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5734 - accuracy: 0.7305
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5729 - accuracy: 0.7310
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5722 - accuracy: 0.7314
Epoch 62/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5716 - accuracy: 0.7311
Epoch 63/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5711 - accuracy: 0.7323
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5702 - accuracy: 0.7306
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5686 - accuracy: 0.7332
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5671 - accuracy: 0.7332
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5660 - accuracy: 0.7332
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5654 - accuracy: 0.7336
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5650 - accuracy: 0.7332
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5648 - accuracy: 0.7329
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5644 - accuracy: 0.7337
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5642 - accuracy: 0.7334
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5640 - accuracy: 0.7334
Epoch 74/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5639 - accuracy: 0.7324
Epoch 75/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5636 - accuracy: 0.7338
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5633 - accuracy: 0.7331
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5625 - accuracy: 0.7338
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5617 - accuracy: 0.7336
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5606 - accuracy: 0.7322
Epoch 80/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5594 - accuracy: 0.7332
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5585 - accuracy: 0.7332
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5577 - accuracy: 0.7333
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5574 - accuracy: 0.7330
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5565 - accuracy: 0.7332
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5563 - accuracy: 0.7331
Epoch 86/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5559 - accuracy: 0.7336
Epoch 87/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5555 - accuracy: 0.7338
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5550 - accuracy: 0.7327
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5547 - accuracy: 0.7338
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5543 - accuracy: 0.7333
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5539 - accuracy: 0.7333
Epoch 92/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5536 - accuracy: 0.7336
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5533 - accuracy: 0.7335
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5530 - accuracy: 0.7341
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5529 - accuracy: 0.7338
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5527 - accuracy: 0.7334
Epoch 97/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5524 - accuracy: 0.7339
Epoch 98/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5522 - accuracy: 0.7342
Epoch 99/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5522 - accuracy: 0.7347
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5520 - accuracy: 0.7337

In [39]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5564 - accuracy: 0.7317 - 567ms/epoch - 2ms/step
Loss: 0.5564107298851013, Accuracy: 0.7316617965698242

In [40]:
# Export our model to HDF5 file
model_filename = 'model_loss.h5'

# Save the model to an HDF5 file
tf.keras.models.save_model(nn_model, model_filename)

<ipython-input-40-aa7c46e92cf5>:5: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  tf.keras.models.save_model(nn_model, model_filename)